src/Entity/Emprunt.php
<?php

namespace App\Entity;

use App\Repository\EmpruntRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EmpruntRepository::class)
 */
class Emprunt
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_emprunt;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_retour;

    /**
     * @ORM\ManyToOne(targetEntity=Livre::class, inversedBy="emprunts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $livre;

    /**
     * @ORM\ManyToOne(targetEntity=Abonne::class, inversedBy="emprunts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $abonne;
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateEmprunt(): ?\DateTimeInterface
    {
        return $this->date_emprunt;
    }

    public function setDateEmprunt(\DateTimeInterface $date_emprunt): self
    {
        $this->date_emprunt = $date_emprunt;

        return $this;
    }

    public function getDateRetour(): ?\DateTimeInterface
    {
        return $this->date_retour;
    }

    public function setDateRetour(?\DateTimeInterface $date_retour): self
    {
        $this->date_retour = $date_retour;

        return $this;
    }

    public function getLivre(): ?Livre
    {
        return $this->livre;
    }

    public function setLivre(?Livre $livre): self
    {
        $this->livre = $livre;

        return $this;
    }

    public function getAbonne(): ?Abonne
    {
        return $this->abonne;
    }

    public function setAbonne(?Abonne $abonne): self
    {
        $this->abonne = $abonne;

        return $this;
    }
}

src/Form/EmpruntType.php
<?php

namespace App\Form;

use App\Entity\Abonne;
use App\Entity\Emprunt;
use App\Entity\Livre;
use DateTime;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmpruntType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_emprunt',DateType::class,[
                "widget" => "single_text",
                "label" => "Emprunté le ",
               // "empty_data" => new DateTime("now") // ne change rien pour un DateType
               // "data" => new DateTime("now") //à ne pas utiliser si le EmpruntType est utilisé pour les modifications 
            ])
            ->add('date_retour',DateType::class,[
                "widget" => "single_text",
                "label" => "Rendu le",
                "required"=> false
            ])
            ->add('livre',EntityType::class,[
                "class" => Livre::class,
                "choice_label" => "titre",
                "placeholder" => "Choisissez un livre..."
            ])
            ->add('abonne',EntityType::class,[
                "class" => Abonne::class,
                "choice_label" => "pseudo",
                "placeholder" => "Choisissez un abonné..."
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Emprunt::class,
        ]);
    }
}

src/Controller/EmpruntController.php
<?php

namespace App\Controller;

use App\Entity\Emprunt;
use App\Form\EmpruntType;
use App\Repository\EmpruntRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/emprunt')]
class EmpruntController extends AbstractController
{
    #[Route('/', name: 'emprunt_index', methods: ['GET'])]
    public function index(EmpruntRepository $empruntRepository): Response
    {
        return $this->render('emprunt/index.html.twig', [
            'emprunts' => $empruntRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'emprunt_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $emprunt = new Emprunt();
        $form = $this->createForm(EmpruntType::class, $emprunt);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($emprunt);
            $entityManager->flush();

            return $this->redirectToRoute('emprunt_index');
        }

        return $this->render('emprunt/new.html.twig', [
            'emprunt' => $emprunt,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'emprunt_show', methods: ['GET'])]
    public function show(Emprunt $emprunt): Response
    {
        return $this->render('emprunt/show.html.twig', [
            'emprunt' => $emprunt,
        ]);
    }

    #[Route('/{id}/edit', name: 'emprunt_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Emprunt $emprunt): Response
    {
        $form = $this->createForm(EmpruntType::class, $emprunt);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('emprunt_index');
        }

        return $this->render('emprunt/edit.html.twig', [
            'emprunt' => $emprunt,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'emprunt_delete', methods: ['POST'])]
    public function delete(Request $request, Emprunt $emprunt): Response
    {
        if ($this->isCsrfTokenValid('delete'.$emprunt->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($emprunt);
            $entityManager->flush();
        }

        return $this->redirectToRoute('emprunt_index');
    }
}

templates/emprunt/_delete_form.html.twig
<form method="post" action="{{ path('emprunt_delete', {'id': emprunt.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ emprunt.id) }}">
    <button class="btn">Delete</button>
</form>

templates/emprunt/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/emprunt/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Emprunt{% endblock %}

{% block body %}
    <h1>Edit Emprunt</h1>

    {{ include('emprunt/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('emprunt_index') }}">back to list</a>

    {{ include('emprunt/_delete_form.html.twig') }}
{% endblock %}

templates/emprunt/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Emprunt index{% endblock %}

{% block body %}
    <h1>Emprunt index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Abonné</th>
                <th>Livre</th>
                <th>Date_emprunt</th>
                <th>Date_retour</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for emprunt in emprunts %}
            <tr>
                <td>{{ emprunt.id }}</td>
                <td>{{emprunt.abonne.pseudo}}</td>
                <td>{{emprunt.livre.titre}}</td>
                <td>{{ emprunt.dateEmprunt ? emprunt.dateEmprunt|date('d/m/y') : '' }}</td>
                <td>{{ emprunt.dateRetour ? emprunt.dateRetour|date('d/m/y') : '' }}</td>
                <td>
                    <a href="{{ path('emprunt_show', {'id': emprunt.id}) }}"><i class="fas fa-eye"></i>
                    show</a>
                    <a href="{{ path('emprunt_edit', {'id': emprunt.id}) }}"><i class="fas fa-edit"></i>
                    edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('emprunt_new') }}">Create new</a>
{% endblock %}

templates/emprunt/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Emprunt{% endblock %}

{% block body %}
    <h1>Create new Emprunt</h1>

    {{ include('emprunt/_form.html.twig') }}

    <a href="{{ path('emprunt_index') }}">back to list</a>
{% endblock %}

templates/emprunt/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Emprunt{% endblock %}

{% block body %}
    <h1>Emprunt</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ emprunt.id }}</td>
            </tr>
            <tr>
                <th>Date_emprunt</th>
                <td>{{ emprunt.dateEmprunt ? emprunt.dateEmprunt|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_retour</th>
                <td>{{ emprunt.dateRetour ? emprunt.dateRetour|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('emprunt_index') }}">back to list</a>

    <a href="{{ path('emprunt_edit', {'id': emprunt.id}) }}">edit</a>

    {{ include('emprunt/_delete_form.html.twig') }}
{% endblock %}